psql:
  image: kobotoolbox/psql:latest
  # build: ./base_images/psql
  hostname: psql
  volumes:
    - "./.vols/db:/srv/db"
  restart: on-failure

odkaggregate:
  image: kobotoolbox/odk-aggregate:latest
  #build: ./base_images/odk-aggregate
  env_file:
    - ./envfile.local.txt
  links:
    - psql
  volumes:
    - "./.vols/../log/odkaggregate:/usr/local/tomcat/logs"
    - ./scripts/wait_for_postgres.bash:/etc/my_init.d/00_wait_for_postgres.bash:ro
  restart: always

geoserver:
  image: kobotoolbox/geoserver:latest
  #build: ./base_images/geoserver
  env_file:
    - ./envfile.local.txt
  links:
    - psql
  volumes:
   - "./.vols/../log/geoserver:/usr/local/tomcat/logs" 
   - "./.vols/geoserver:/srv/geoserver"
   - ./scripts/geoserver_chown.bash:/etc/my_init.d/00_geoserver_chown.bash
   - ./scripts/wait_for_geoserver.bash:/etc/my_init.d/02_wait_for_geoserver.bash:ro
  environment:
    - GEOSERVER_DATA_DIR=/srv/geoserver
  restart: always

nginx:
  image: kobotoolbox/nginx:latest
  # build: ./base_images/nginx
  hostname: nginx
  env_file:
    - ./envfile.local.txt
  environment:
    - NGINX_CONFIG_FILE_NAME=nginx_site_http.conf
    - NGINX_DEBUG_kpi=False
    - NGINX_DEBUG_kobocat=False
  ports:
    # NOTE: The host ports (left of the ":") must match the values in `envfile.local.txt`. Do not modify the right hand side values (9000+).
    - 8005:9005 # Enketo Express
    - 8006:9006 # ODK
    - 8007:9007 # GeoServer
  volumes:
      - "./.vols/static:/srv/www:ro"
      # get the logs out of glusterfs!
      - "./.vols/../log/nginx:/var/log/nginx"
      - ./nginx/:/tmp/kobo_nginx/:ro
      - ./nginx/nginx_command.bash:/etc/service/nginx/run:ro
  links:
    - enketo_express
    - odkaggregate
    - geoserver
  restart: on-failure

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
enketo_express:
  image: kobotoolbox/enketo_express
  # build: ../enketo-express/
  env_file:
    - ./envfile.local.txt
  links:
    - redis_main
    - redis_cache
  restart: on-failure
  volumes:
    - ./scripts/computed_vars.local.source.bash:/etc/profile.d/enketo_express_computed_vars.source.bash.sh:ro
    - ./enketo_express/config.json:/srv/tmp/enketo_express_config.json:ro
    - ./scripts/enketo_express_copy_config.bash:/etc/my_init.d/01_enketo_express_copy_config.bash:ro
    - ./enketo_express/odk_color.png:/srv/src/enketo_express/public/images/odk_color.png:ro

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
redis_main:
  image: redis:2.6
  # Map our "main" Redis config into the container.
  volumes:
    - ./redis/redis-enketo-main.conf:/etc/redis/redis.conf
    - "./.vols/redis_main_data/:/data/"
  restart: on-failure

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
redis_cache:
  image: redis:2.6
  # Map our "cache" Redis config into the container.
  volumes:
    - ./redis/redis-enketo-cache.conf:/etc/redis/redis.conf
  restart: on-failure
